CREATE TABLE `credit_risk`.`companies`
(
    `SessionID` VARCHAR(100) NOT NULL,
    `ID`        INT          NOT NULL,
    `Field1`    FLOAT NULL,
    `Field2`    FLOAT NULL,
    `Field3`    FLOAT NULL,
    `Field4`    FLOAT NULL,
    `Field5`    FLOAT NULL,
    `Field6`    FLOAT NULL,
    `Field7`    FLOAT NULL,
    `Field8`    FLOAT NULL,
    `Field9`    FLOAT NULL,
    `Field10`   FLOAT NULL,
    `Date`      DATE         NOT NULL,
    `Model`     CHAR(10)     NOT NULL,
    `Factor1`   FLOAT NULL,
    `Factor2`   FLOAT NULL,
    `Factor3`   FLOAT NULL,
    `Factor4`   FLOAT NULL,
    `Factor6`   FLOAT NULL,
    `Factor7`   FLOAT NULL,
    `LPT`       FLOAT NULL,
    `BEH`       FLOAT NULL,
    `FIN`       FLOAT NULL,
    `TOTAL`     DOUBLE       NOT NULL,
    UNIQUE `SessionID` (`SessionID`)
)